spring:
  application:
    name: mail-service
  kafka:
    bootstrap-servers: localhost:9092
  mail:
    host: smtp.gmail.com
    port: 587
    username: kkraken2005@gmail.com
    password: password
    protocol: mail.transport.protocol
    protocolType: smtp
    mailDebug: mail.debug
    danekerscode: true
    enable: mail.smtp.starttls.enable
server:
  port: 8083
